services:
  go-app:
    build: .
    image: go-app-v2:latest
    container_name: go-app-final
    restart: always
    environment:
      - APP_PORT=9001
      - APP_ENV=Production-Preview
    ports:
      - "9001:9001"
    networks:
      - dev_edu-network-dev

networks:
  dev_edu-network-dev:
    external: true
